Create sv_SE.json
NamelessMC/Nameless-Link pull request #183
Opened 2021-07-09 15:37 UTC by ItsLynix

Swedish added :)

2021-07-24 21:44 UTC, Derkades requested changes
Thanks! I don't speak Swedish so I can't comment much, but I did notice a few minor typos

2021-07-24 21:44 UTC, Derkades commented on src/main/resources/languages/sv_SE.json
> +    "error_generic": "Ett internt  fel uppstod.",
Double space

2021-07-24 21:44 UTC, Derkades commented on src/main/resources/languages/sv_SE.json
> +    "help_context_content": "Vissa kommandon är bara tillgängliga i  DMs,  medan andra bara är tillgängliga i servers.",
Double space

2021-07-24 21:44 UTC, Derkades commented on src/main/resources/languages/sv_SE.json
> +    "apiurl_try_https": "Din API-URL använder http: //. Om du använder en proxy för HTTPS visar webbplatsen fortfarande HTTP API-URL: er. Försök att köra det här kommandot igen och ersätt http: // me
Are you sure about the unusual space after `http:`?

2021-07-24 21:44 UTC, Derkades commented on src/main/resources/languages/sv_SE.json
> +    "apiurl_url_invalid": "Den angivna API-URL: en ser inte ut som en NamelessMC API URL. Du hittar API-URL: en i StaffKP> Konfiguration> API.",
Space before `>` for consistency please

2021-08-12 22:03 UTC, ItsLynix commented
I wrote the double spaces with a broken keyboard on accident, and the space after http is not supposed to be there, I've been on vacation for almost a month, but I'm now back to correct this, thanks for telling me. Really shows the quality control on this stuff.

2021-08-12 22:05 UTC, ItsLynix reviewed
I've fixed the errors now..

2021-08-23 08:58 UTC, Derkades approved these changes
still a couple unfixed issues but I'll just fix those myself after merging

2021-08-23 08:58 UTC, merged

2021-08-23 09:14 UTC, ItsLynix commented
Apologies for some of the issues, working with a broken keyboard isn't really too reliable in editing