Adding the possibility for an individual prefix
NamelessMC/Nameless-Link pull request #99
Opened 2021-02-10 21:03 UTC by Taucher2003

This closes https://github.com/NamelessMC/Nameless-Link/issues/54

2021-02-10 21:15 UTC, Derkades requested changes

2021-02-10 21:15 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/Command.java
> +		if(!message.getContentRaw().startsWith(Main.getCommandPrefix()))
A bit of a nitpick but can you add a space after `if` and add braces

2021-02-10 21:15 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/Command.java
> +						.addField(language.get(Term.HELP), s.replace("{prefix}", Main.getCommandPrefix()), false).build()).queue();
Is there any reason you don't just use `Main.getCommandPrefix()` directly on line 75? At that time it is already known so I don't understand why you build the string with a placeholder and replace the placeholder later

2021-02-10 21:15 UTC, Derkades commented on src/main/java/com/namelessmc/bot/Main.java
> +import com.namelessmc.bot.commands.*;
not really a fan of .* imports but the next time I edit this file my IDE will fix it anyway

2021-02-10 21:23 UTC, Taucher2003 commented on src/main/java/com/namelessmc/bot/commands/Command.java
> +						.addField(language.get(Term.HELP), s.replace("{prefix}", Main.getCommandPrefix()), false).build()).queue();
Good point, propably I just didn't thinked so far as it is a bit late for me

2021-02-10 21:24 UTC, Taucher2003 commented on src/main/java/com/namelessmc/bot/Main.java
> +import com.namelessmc.bot.commands.*;
IntelliJ automatically uses a Wildcard import if there are to many imports from the same package. I didn't noticed that there

2021-02-10 21:25 UTC, Taucher2003 commented on src/main/java/com/namelessmc/bot/commands/Command.java
> +		if(!message.getContentRaw().startsWith(Main.getCommandPrefix()))
The next time I let IntelliJ reformat the code you automatically get your wish

2021-02-10 21:29 UTC, Taucher2003 commented
> I also considered allowing it to be set per guild in the database (so people using the central bot can change the prefix) but this is enough for now, adding it to the database adds a lot of complexity.

I wasn't really shure if the bot is used in a selfhosted was or not. That is why I used environment variables. 
After reading your comment, I think it is a managed bot. I will take a look at your database system and will propably implement the per guild prefix.
That is also the reason, was this is a draft PR

2021-02-10 21:31 UTC, Derkades commented
It is both, it can run in a centrally managed mode with a database and it can run self-hosted in "stateless mode" for one discord guild and website.

Outside of DMs, the bot only responds to direct matches of specific commands so the chance of conflict is low.

As a lazy person, I'd say this is fine.

2021-02-11 14:49 UTC, Taucher2003 commented
After merging this PR, you will need to add the `command_prefix` column in your connections database.
The `command_prefix` column is located between `api_url` and `last_use`. The comment to modify the prefix for a guild is also implemented. 

Please note, that these changes are untested as I don't have the possibility to test them. I don't have a Nameless Instance running anywhere. So please, for your own stability of your system, please test these changes before merging and deploying to your production system.

2021-02-16 10:33 UTC, Derkades requested changes

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/Language.java
> -		Term() {
This was so it only used a single empty array instance for all terms without placeholders. Do you know if java optimizes this automatically?

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/connections/ConnectionManager.java
> +	public abstract boolean setCommandPrefix(long guildId, String newPrefix) throws BackendStorageException;
Can you change `newPrefix` to an `Optional<String>` so it is more obvious how to clear the prefix

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/connections/JDBCConnectionManager.java
> +	public boolean setCommandPrefix(long guildId, String newPrefix) throws BackendStorageException {
this to `Optional<String>` and check using `Validate.notBlank`

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/connections/JDBCConnectionManager.java
> +				statement.setString(3, ""); // Empty string means that we use the default prefix
Please use `null` instead

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/connections/JDBCConnectionManager.java
> +				if (prefix == null || prefix.isEmpty() || prefix.isBlank()) {
after other requested changes, only the `== null` check is required (or remove the if entirely and `return Optional.fromNullable(prefix)`)

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/Main.java
> +		if (System.getenv("COMMAND_PREFIX") != null) {
Can you change this to `DEFAULT_COMMAND_PREFIX`, indicating it can be changed like `DEFAULT_LANGUAGE`

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/PrefixCommand.java
> +			message.reply(language.get(Language.Term.UNLINK_GUILD_NOT_LINKED)).queue();
You can use `ERROR_NOT_SET_UP` here

2021-02-16 10:33 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/PrefixCommand.java
> +			message.reply(language.get(Language.Term.UNLINK_GUILD_UNKNOWN)).queue();
`UNLINK_GUILD_UNKNOWN` is a generic error and can be changed to e.g. `ERROR_GUILD_UNKNOWN` so it can be used in multiple places

2021-02-16 10:53 UTC, Taucher2003 commented on src/main/java/com/namelessmc/bot/Language.java
> -		Term() {
```Term(final String... placeholders) {
	this.placeholders = placeholders;
}```
also allows to take 0 arguments. A ... parameter doesn't need to be present

2021-02-16 12:21 UTC, Derkades commented on src/main/java/com/namelessmc/bot/Language.java
> -		Term() {
You are right, but having a separate constructor is faster and saves memory (the internet does not give a clear answer whether java uses scalar replacement for empty varargs).

This is the same reason there are many Set.of methods in addition to the varargs method https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Set.html#of()

2021-02-16 15:18 UTC, Taucher2003 commented on src/main/java/com/namelessmc/bot/connections/JDBCConnectionManager.java
> +	public boolean setCommandPrefix(long guildId, String newPrefix) throws BackendStorageException {
It can not be blank due to the nature of the command.

2021-02-16 15:55 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/PrefixCommand.java
> +			if(!canModifySettings) {
space `if (`

2021-02-16 15:55 UTC, Derkades commented on src/main/java/com/namelessmc/bot/commands/PrefixCommand.java
>  			// This needs to be discussed, if we should use an own translation here as the message would be the same
this comment can now be removed

2021-02-16 15:55 UTC, Derkades commented on src/main/java/com/namelessmc/bot/connections/JDBCConnectionManager.java
> +				statement.setString(3, null); // Empty string means that we use the default prefix
please remove the comment here, it is now out of date

2021-02-16 15:55 UTC, Derkades commented on src/main/resources/languages/nl_NL.json
> +    "error_guild_invalid": "De opgegeven server bestaat niet of is niet verbonden.",
I am confused, neither `unlink_guild_invalid` or `error_guild_invalid` exist in the Term enum, right? Instead of changing it you can probably just remove it.

2021-02-16 15:55 UTC, Derkades commented on src/main/resources/languages/zh_CN.json
> -    "unlink_guild_invalid": "您提供的服务器不存在或者并未被链接。",
same issue as the dutch language file here

2021-02-19 19:15 UTC, Derkades approved these changes

2021-02-19 19:17 UTC, merged

2021-02-19 19:19 UTC, Aberdeener commented
Thanks so much for your contributions :)